CC=mpicc
CXX=mpicxx
CFLAGS=-g -O3 -fopenmp
CXXFLAGS=-g -O3 -fopenmp

AMPI_LIBDIR=../../src
AMPI_INCLUDE=../../include

DCO_LIBDIR=$(HOME)/hg/dco_external_functions/lib
DCO_INCLUDE=$(HOME)/hg/dco_external_functions/include
