CC=mpicc
CXX=mpicxx
CFLAGS=-g -O0 -fopenmp
CXXFLAGS=-g -O0 -fopenmp

AMPI_LIBDIR=../../src
AMPI_INCLUDE=../../include

DCO_LIBDIR=$(HOME)/git/dco/build/dco_cpp/lib
DCO_INCLUDE=$(HOME)/git/dco/build/dco_cpp/include
